local wezterm = require 'wezterm';
return {
  keys = {
    {
      key = 'w',
      mods = 'CMD|CTRL',
      action = wezterm.action.CloseCurrentTab { confirm = true },
    },
    {key='UpArrow', mods='CTRL|SHIFT', action="DisableDefaultAssignment"},
    {key='DownArrow', mods='CTRL|SHIFT', action="DisableDefaultAssignment"},
    {key='PageUp', mods='SHIFT', action="DisableDefaultAssignment"},
    {key='PageDown', mods='SHIFT', action="DisableDefaultAssignment"},
    {key='PageUp', mods='CTRL|SHIFT', action="DisableDefaultAssignment"},
    {key='PageDown', mods='CTRL|SHIFT', action="DisableDefaultAssignment"},
  },
  font = wezterm.font "Hack Nerd Font Mono",
  font_rules = {
    {
      intensity = "Normal",
      font = wezterm.font("Hack Nerd Font Mono", {weight="Regular"}),
    },
    {
      italic = true,
      intensity = "Bold",
      font = wezterm.font("Hack Nerd Font Mono", {italic=true, weight="Bold"}),
    },
    {
      intensity = "Bold",
      font = wezterm.font("Hack Nerd Font Mono", {weight="Bold"}),
    },
  },
  font_size = 17.0,
  font_shaper = "Harfbuzz",
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},
  dpi = 96.0,
  bold_brightens_ansi_colors = true,
  freetype_load_flags = "DEFAULT",
  freetype_render_target = "Normal",
  front_end = "OpenGL",
  prefer_egl = true,
  window_padding = {
    left = 10,
    right = 10,
    top = 0,
    bottom = 0,
  },
  window_decorations = 'RESIZE',
  window_close_confirmation = 'AlwaysPrompt',
  hide_tab_bar_if_only_one_tab = true,
  initial_cols = 300,
  initial_rows = 100,
  enable_tab_bar = false,
  text_background_opacity = 1,
  color_scheme = 'tokyo-night-storm',
  color_schemes = {
    ['tokyo-night-storm'] = {
      foreground = '#c9d3ff',
      background = '#24283b',
      cursor_fg = '#24283b',
      cursor_bg = '#c9d3ff',
      cursor_border = '#c9d3ff',
      selection_bg = '#304A86',
      ansi = {
        '#32344a',
        '#ea4e6b',
        '#9ece6a',
        '#ff9e64',
        '#7aa2f7',
        '#ad8ee6',
        '#75c1ee',
        '#b6b9cc',
      },
      brights = {
        '#444b6a',
        '#ff4266',
        '#ace173',
        '#e0af68',
        '#9abaff',
        '#bb9af7',
        '#7dcfff',
        '#cbcff5',
      },
    },
  },
}
